import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ryan Ahn's NextJs15 Starter",
  description: "Generated by create next app",
  keywords: [
    "ryan-ahn",
    "nextjs",
    "starter",
    "tailwindCSS",
    "typescript",
    "react",
    "nodejs",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
